[[redirects]]
  from = "https://*.esy.com/*"
  to = "https://esy.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://*.esy.com/*"
  to = "https://esy.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://esy.netlify.app;"

[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[context.production.environment]
  CLEAR_CACHE = "true"