[[redirects]]
  from = "https://journal.esy.com/*"
  to = "https://journal.esy.com/:splat"
  status = 200

[[redirects]]
  from = "https://*.esy.com/*"
  to = "https://esy.com/"
  status = 301


[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://esy.com;"


[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "build"

[context.production.environment]
  CLEAR_CACHE = "true"
