# Redirect rules

[[redirects]]
 from = "/"
  to = "/research"
  status = 302
  force = true

[[redirects]]
  from = "https://*.esy.com/*"
  to = "https://www.esy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://*.esy.com/*"
  to = "https://esy.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/essays/*"
  to = "https://esy-news.ghost.io/essays/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "www.esy.com"}

[[redirects]]
  from = "/essays"
  to = "https://esy-news.ghost.io/essays/"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "www.esy.com"}

# Exclude assets from redirect
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/page-data/*"
  to = "/page-data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://www.esy.com;"

# Build settings
[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

# Environment settings for production
[context.production.environment]
  CLEAR_CACHE = "true"