[[redirects]]
  from = "https://*.esy.com/*"
  to = "https://www.esy.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://*.esy.com/*"
  to = "https://esy.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/news/*"
  to = "https://esy-news.ghost.io/news/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "esy.com"}

[[redirects]]
  from = "/news"
  to = "https://esy-news.ghost.io/news/"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "esy.com"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://www.esy.com;"

[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[context.production.environment]
  CLEAR_CACHE = "true"